version: "2"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "80:8080"
    restart: always
    command: "python server.py"
    
  service_redis:
    image: redis
    expose:
      - 6379
    restart: always

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: "rq worker -u redis://service_redis:6379"
