version: "3.5"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "80:8080"
    restart: always
    command: "python server.py"
    
  redis:
    container_name: redis
    expose:
      - 6379
    restart: always

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: "rq worker"
